### ISSUE TITLE
TypeError: genieScx.load is not a function

### ISSUE THREAD

**Issue by TLHP** [genie-js/genie-scx#4]
Hi team, 

Great tool for AoE SCX reader :x 
I am new for nodejs and I have problem calling your lib

TypeError: genieScx.load is not a function

```js
server.listen(port, hostname, () => {
  	console.log(`Server running at http://${hostname}:${port}/`);
	console.log(mapFile);
	genieScx.load(mapFile, (err, data) => {
		console.log(data);
	});
});
```

Can you help?

**Comment by goto-bus-stop** [comment]
The documentation in the repository is for recent changes, the version you get from `npm install genie-scx` is a bit different. npm has the documentation for that version: https://www.npmjs.com/package/genie-scx

Instead of `genieScx.load(buffer, callback)`, you have to do `genieScx(buffer).parse(callback)`.

sorry for the confusion!

**Comment by TLHP** [comment]
Thanks it compiles now.

I tried with scx from Scenario Builder but error appeared:

```
buffer.js:977
    throw new RangeError('Index out of range');
    ^

RangeError: Index out of range
    at checkOffset (buffer.js:977:11)
    at Buffer.readUInt32LE (buffer.js:1039:5)
    at Function.read (/Users/tinguyen/node_modules/awestruct/lib/types.js:52:36)
    at Function.read (/Users/tinguyen/node_modules/awestruct/lib/StructType.js:23:15)
    at /Users/tinguyen/node_modules/awestruct/lib/Struct.js:60:24
    at Array.forEach (<anonymous>)
    at Function.decode (/Users/tinguyen/node_modules/awestruct/lib/Struct.js:56:12)
    at Function.read (/Users/tinguyen/node_modules/awestruct/lib/StructType.js:23:15)
    at Function.read (/Users/tinguyen/node_modules/awestruct/lib/types.js:123:31)
    at Function.read (/Users/tinguyen/node_modules/awestruct/lib/StructType.js:23:15
)
```
Can you try this one ? SCX file: https://ufile.io/n8oy4

**Comment by TLHP** [comment]
Its just a problem of scx version (yours for latest version of scx, mine is 1.11).
We can close this issue
